// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getUsersByName.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT FROM 
  users
WHERE
  name = $1
`

type GetUserRow struct {
}

func (q *Queries) GetUser(ctx context.Context, name string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i GetUserRow
	err := row.Scan()
	return i, err
}
