// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markedFeedFetched.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const markedFeedFetched = `-- name: MarkedFeedFetched :exec
UPDATE 
  feeds 
SET
  last_fetched_at = $1,
  updated_at = $2
WHERE 
  id = $3
`

type MarkedFeedFetchedParams struct {
	LastFetchedAt sql.NullTime
	UpdatedAt     time.Time
	ID            uuid.UUID
}

func (q *Queries) MarkedFeedFetched(ctx context.Context, arg MarkedFeedFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markedFeedFetched, arg.LastFetchedAt, arg.UpdatedAt, arg.ID)
	return err
}
